docs: Create CONTRIBUTING.md file
bartekpacia/mentorship-client pull request #21
Opened 2020-04-18 16:53 UTC by gaurivn

### Description
Created CONTRIBUTING.md file.

Fixes #2 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- Documentation

**Code/Quality Assurance Only**

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation

2020-04-18 16:56 UTC, techno-disaster requested changes

2020-04-18 16:56 UTC, Techno-Disaster commented on CONTRIBUTING.md
> +* Use only the latest stable version of Flutter.
beta version

2020-04-18 16:56 UTC, Techno-Disaster commented
@isabelcosta please review this, and confirm if any changes are required

2020-04-18 17:00 UTC, gaurivn commented on CONTRIBUTING.md
> +* Use only the latest stable version of Flutter.
@Techno-Disaster  done.

2020-04-18 17:15 UTC, isabelcosta requested changes
Two minor changes and this is fine :D 
Thank you for your contribution @gaurivn !

2020-04-18 17:15 UTC, isabelcosta commented on CONTRIBUTING.md
> +* You can join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/).  Each active repo has its own stream to direct questions to (for example #powerup or #portal).  Mentorship Syst
```suggestion
* You can join us on [AnitaB.org Open Source Zulip](https://anitab-org.zulipchat.com/).  Each active repo has its own stream to direct questions to (for example #powerup or #portal).  Mentorship System stream is [#mentorship-system](https://anitab-org.zulipchat.com/#narrow/stream/222534-mentorship-system).
```

Even though there is a flutter topic, to discuss the project in itself as a product as a whole and its counterparts, you just need to know about the stream. The topics can change over time and all.

2020-04-18 17:15 UTC, isabelcosta commented on CONTRIBUTING.md
> +* If you’re just getting started work on an issue labeled “First Timers Only” in any project. Additional resources are available on our [website](http://www.systers.io).
```suggestion
* If you’re just getting started work on an issue labeled “First Timers Only” in any project.
```
Systers.io is going to be sunset, so no need to add that :)

2020-04-18 17:31 UTC, gaurivn commented
@isabelcosta ,thank you, I made changes, please review them, you are welcome.

2020-04-19 21:14 UTC, Techno-Disaster commented
@gaurivn once you update the requested changes please re request a review so that we can review it and merge it asap

2020-04-19 21:18 UTC, gaurivn commented
@Techno-Disaster , I have made the requested changes. I will request for review.

2020-04-19 21:28 UTC, techno-disaster approved these changes

2020-04-19 21:36 UTC, isabelcosta approved these changes
Great work @gaurivn 🎉

2020-04-19 21:36 UTC, merged

2020-04-19 21:36 UTC, gaurivn commented
Thank you @isabelcosta