feat: add "Both" checkbox on SignUp page
bartekpacia/mentorship-client pull request #75
Opened 2020-05-17 21:20 UTC by Techno-Disaster

### Description
Added a Both checkbox on signup page for user convience. All edge cases have been tested, check gif below
Fixes #59 

### Flutter Channel:
- [x] I have used the Flutter Beta channel on my local machine 

### Type of Change:
**Delete irrelevant options.**

- User Interface

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

### How Has This Been Tested?
Physical Device. 
![2020_05_18_02_37_53](https://user-images.githubusercontent.com/52817235/82160321-14df4a80-98b2-11ea-89d8-997ff1ed102c.gif)

### Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

2020-05-17 21:22 UTC, Techno-Disaster commented
@anitab-org/qa-team can someone test this PR locally too? just to be sure

2020-05-17 21:29 UTC, Techno-Disaster commented
@anitab-org/mentorship-flutter-maintainers The failed check is clearly a Travis error, refer to the [checks](https://github.com/anitab-org/mentorship-flutter/pull/75/checks) tab for results

2020-05-17 21:38 UTC, Techno-Disaster commented
> @anitab-org/mentorship-flutter-maintainers The failed check is clearly a Travis error, refer to the [checks](https://github.com/anitab-org/mentorship-flutter/pull/75/checks) tab for results

Re-run the build to remove errors

2020-05-18 08:29 UTC, bartekpacia commented
Nice, but why `both` is a separate option?

2020-05-18 15:33 UTC, Techno-Disaster commented
@bartekpacia thats what was asked by Isabel in the issue #59

2020-05-18 18:08 UTC, foongminwong approved these changes
Tested locally on Android 8.0:
![VID-20200518-130113](https://user-images.githubusercontent.com/23441795/82245378-74684500-9908-11ea-877c-c97059baf89e.GIF)

2020-05-18 18:12 UTC, Techno-Disaster commented
thanks @foongminwong

2020-05-19 09:40 UTC, bartekpacia approved these changes
Nice job:)

2020-05-19 19:36 UTC, isabelcosta requested changes
It should be radio buttons instead of checkboxes, because it is a single option selection and not a multiple selection group @Techno-Disaster 
Thank you @foongminwong for providing visual proof

2020-05-19 21:19 UTC, Techno-Disaster commented
> It should be radio buttons instead of checkboxes, because it is a single option selection and not a multiple selection group @Techno-Disaster
> Thank you @foongminwong for providing visual proof

@isabelcosta what do you mean by "radio buttons" ? The current buttons behave the same way. Can you explain exactly what functionality you are looking for?

2020-05-19 21:35 UTC, foongminwong commented
> > It should be radio buttons instead of checkboxes, because it is a single option selection and not a multiple selection group @Techno-Disaster
> > Thank you @foongminwong for providing visual proof
> 
> @isabelcosta what do you mean by "radio buttons" ? The current buttons behave the same way. Can you explain exactly what functionality you are looking for?

Hmm, this reminded me one of the latest pull requests on mentorship-android, check out [these pictures](https://github.com/anitab-org/mentorship-android/pull/686#pullrequestreview-399298149) about the radio buttons that @isabelcosta mentioned

2020-05-19 21:40 UTC, Techno-Disaster commented
> > > It should be radio buttons instead of checkboxes, because it is a single option selection and not a multiple selection group @Techno-Disaster
> > > Thank you @foongminwong for providing visual proof
> > 
> > 
> > @isabelcosta what do you mean by "radio buttons" ? The current buttons behave the same way. Can you explain exactly what functionality you are looking for?
> 
> Hmm, this reminded me one of the latest pull requests on mentorship-android, check out [these pictures](https://github.com/anitab-org/mentorship-android/pull/686#pullrequestreview-399298149) about the radio buttons that @isabelcosta mentioned

But when "both" button is clicked shouldn't the mentor and mentee both be selected automatically? Other wise the user may wonder what this "both" button actually selects. 
In my opinion @isabelcosta we should keep this the way it is, from a UX point of view, and the Android client should also move onto this. What do you think? 
cc @bartekpacia @foongminwong

2020-05-21 16:10 UTC, bartekpacia commented
I'd lean towards simply using 2 checkboxes: (available to be) "Mentee" and "Mentor". "Both" checkbox is redundant, and radio buttons are meant for single-choice, not multi-choice.

2020-05-21 17:08 UTC, closed without merging

2020-05-21 17:22 UTC, Techno-Disaster commented
> I'd lean towards simply using 2 checkboxes: (available to be) "Mentee" and "Mentor". "Both" checkbox is redundant, and radio buttons are meant for single-choice, not multi-choice.

Hey Bartek, we discussed this in the community sessions today and decided to stick with radio buttons. Sending a new PR soon :)